package com.vlrclone.backend.Enums;

public enum NotificationType {
    EVENT_CREATED,
    EVENT_UPDATED,
    EVENT_ANNOUNCEMENT,
    CLUB_ANNOUNCEMENT,
    CLUB_JOINED,
    THREAD_COMMENTED,
    POST_COMMENTED,
    COMMENT_REPLY,
    EVENT_INTERESTED,
    CLUB_ESCALATION,
}